# codecov.yml
coverage:
  status:
    project:
      # This creates separate status checks on your PRs for each flag
      default: false
      main-process:
        target: auto
        flags:
          - main-process
      renderer-process:
        target: auto
        flags:
          - renderer-process

flags:
  main-process:
    carryforward: true
    paths:
      - src/main/          # STRICTLY track the main process here
  renderer-process:
    carryforward: true
    paths:
      - src/renderer/      # STRICTLY track the renderer here
