import { app, BrowserWindow, dialog, ipcMain, clipboard } from 'electron';
import fs from 'fs';
import Excel from 'exceljs';
import { dataParser, DataErrorHandler } from './dataInput';
import { Camp } from './camp';
import { Kids } from './kids';
import { Schedule } from './schedule';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let CAMP_BEST_SCHEDULE: Schedule | null = null;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1000,
    minHeight: 650,
    width: 1200,
    minWidth: 650,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false, // ← Add this line
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  mainWindow.once('ready-to-show', () => {
    setTimeout(() => {
      mainWindow.webContents.reloadIgnoringCache();
      mainWindow.show();
    }, 600); // Give the local Webpack dev server 600ms to pipe the React compilation
  });
  // Open file Dialog for user to pick file.
  ipcMain.handle('open-file-dialog', async () => {
    const result = await dialog.showOpenDialog({
      properties: ['openFile'],
      filters: [{ name: 'Sheets', extensions: ['xlsx'] }],
    });

    const workbook = new Excel.Workbook();
    await workbook.xlsx.readFile(result.filePaths[0]);
    let data = '';
    workbook.worksheets[0].eachRow({ includeEmpty: true }, function (row) {
      let s = JSON.stringify(row.values);
      s = s.replace(/\[null,"|"\]/g, '');
      s = s.replace(/","|",|,"/g, '\t');
      data += s + '\n';
    });
    const { allErrors, dataErrors } = handleErrors(data);
    if (!allErrors.every(item => item === false)) {
      mainWindow.webContents.send('error-list', JSON.stringify(dataErrors.getErrorList()));
    } else {
      const result = scheduleKids(data);
      if (result) {
        mainWindow.webContents.send('result-list', JSON.stringify(result));
      } else {
        mainWindow.webContents.send(
          'error-list',
          JSON.stringify([
            {
              header: 'Unable to schedule kids',
              errorList: [
                'This is most likely due to way too many kids making the same choice or there are not enough total kids attending.',
              ],
            },
          ])
        );
      }
    }
  });

  // Handle input via the pastebox
  ipcMain.handle('submit-text', async (event, data) => {
    const { allErrors, dataErrors } = handleErrors(data);
    if (!allErrors.every(item => item === false)) {
      mainWindow.webContents.send('error-list', JSON.stringify(dataErrors.getErrorList()));
    } else {
      const result = scheduleKids(data);
      if (result) {
        mainWindow.webContents.send('result-list', JSON.stringify(result));
      } else {
        mainWindow.webContents.send(
          'error-list',
          JSON.stringify([
            {
              header: 'Unable to schedule kids',
              errorList: [
                'This is most likely due to way too many kids making the same choice or there are not enough total kids attending.',
              ],
            },
          ])
        );
      }
    }
  });

  ipcMain.handle('copy-schedule', async (event, data) => {
    clipboard.writeText(data);
    mainWindow.webContents.send('clipboard-content', 'notification-box');
  });

  ipcMain.handle(
    'export-excel',
    async (event, result, waterActs: string[], land9amActs: string[], land10amActs: string[]) => {
      const workbook = new Excel.Workbook();
      const activityWS = workbook.addWorksheet('By Activity');

      // Define columns (optional but recommended for object-based row addition)
      activityWS.columns = [
        { header: 'Activity Time', key: 'time', width: 15 },
        { header: 'Activity', key: 'activity', width: 12 },
        { header: 'Kid Count', key: 'count', width: 10 },
        { header: 'Names', key: 'names', width: 200 },
      ];

      const allActivities = waterActs.concat(waterActs, land9amActs, land10amActs);
      const activityTimes = Array(waterActs.length)
        .fill('Water 9AM')
        .concat(
          Array(waterActs.length).fill('Water 10AM'),
          Array(land9amActs.length).fill('Land 9AM'),
          Array(land10amActs.length).fill('Land 10AM')
        );

      // Add data rows
      for (let i = 0; i < allActivities.length; i++) {
        const timeSlot = activityTimes[i].toLowerCase().replaceAll(' ', '');
        const kids = result[timeSlot][allActivities[i]];
        const kidsCount = kids.length;
        activityWS.addRow({
          time: activityTimes[i],
          activity: allActivities[i],
          count: kidsCount,
          names: joinNames(kids),
        });
      }

      const nameWS = workbook.addWorksheet('By Name');

      // Define columns (optional but recommended for object-based row addition)
      nameWS.columns = [
        { header: 'Name', key: 'name', width: 25 },
        { header: 'Water Time', key: 'waterTime', width: 15 },
        { header: 'Water Activity', key: 'waterActivity', width: 12 },
        { header: 'Land Time', key: 'landTime', width: 15 },
        { header: 'Land Activity', key: 'landActivity', width: 12 },
      ];

      for (const name of result.kids.names.sort()) {
        if (!CAMP_BEST_SCHEDULE) {
          continue; // Skip or handle missing schedule data appropriately
        }
        let waterTime = '10am';
        let waterActivity = CAMP_BEST_SCHEDULE.schedule.get(name)?.['timeSlots']['water10am'];
        if (CAMP_BEST_SCHEDULE.schedule.get(name)?.['timeSlots']['water9am'] !== null) {
          waterTime = '9am';
          waterActivity = CAMP_BEST_SCHEDULE.schedule.get(name)?.['timeSlots']['water9am'];
        }
        let landTime = '10am';
        let landActivity = CAMP_BEST_SCHEDULE.schedule.get(name)?.['timeSlots']['land10am'];
        if (CAMP_BEST_SCHEDULE.schedule.get(name)?.['timeSlots']['land9am'] !== null) {
          landTime = '9am';
          landActivity = CAMP_BEST_SCHEDULE.schedule.get(name)?.['timeSlots']['land9am'];
        }

        nameWS.addRow({
          name: name,
          waterTime: waterTime,
          waterActivity: waterActivity,
          landTime: landTime,
          landActivity: landActivity,
        });
      }

      const buffer = await workbook.xlsx.writeBuffer();
      const { filePath, canceled } = await dialog.showSaveDialog({
        title: 'Save NY Kids Camp Workbook',
        filters: [{ name: 'Excel Files', extensions: ['xlsx'] }],
      });
      if (!canceled && filePath) {
        fs.writeFileSync(filePath, buffer as unknown as Uint8Array);
      }
    }
  );
  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

const joinNames = (names: string[]): string => {
  if (names.length === 0) {
    return 'No kids scheduled';
  }
  let nameOrder = '';
  names.forEach(name => {
    const [last, first] = name.split(/\s+/);
    const inOrder = `${first} ${last}, `;
    nameOrder += inOrder;
  });
  return nameOrder.slice(0, -2);
};

const scheduleKids = (data: string) => {
  const kids = new Kids(data);
  const camp = new Camp(kids);
  camp.scheduleTheKids(100);
  CAMP_BEST_SCHEDULE = camp.bestSchedule;
  return camp.bestSchedule;
};

const handleErrors = (data: string) => {
  const { campData, headerRow } = dataParser(data);
  const dataErrors = new DataErrorHandler(campData, headerRow);
  const allErrors: boolean[] = [
    dataErrors.numOfFields(),
    dataErrors.wrongActivity(),
    dataErrors.notEnoughKids(),
    dataErrors.tooManyKids(),
  ];
  return { allErrors, dataErrors };
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
