import { app, BrowserWindow, dialog, ipcMain, clipboard } from 'electron';
import fs from 'fs';
import Excel from 'exceljs';
import { dataParser, DataErrorHandler } from './dataInput';
import { Camp } from './camp';
import { Kids } from './kids';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1000,
    minHeight: 650,
    width: 1200,
    minWidth: 650,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open file Dialog for user to pick file.
  ipcMain.handle('open-file-dialog', async () => {
    const result = await dialog.showOpenDialog({
      properties: ['openFile'],
      filters: [{ name: 'Sheets', extensions: ['xlsx'] }],
    });

    const workbook = new Excel.Workbook();
    await workbook.xlsx.readFile(result.filePaths[0]);
    let data = '';
    workbook.worksheets[0].eachRow({ includeEmpty: true }, function (row) {
      let s = JSON.stringify(row.values);
      s = s.replace(/\[null,"|"\]/g, '');
      s = s.replace(/","|",|,"/g, '\t');
      data += s + '\n';
    });
    const { allErrors, dataErrors } = handleErrors(data);
    if (!allErrors.every(item => item === false)) {
      mainWindow.webContents.send('error-list', JSON.stringify(dataErrors.getErrorList()));
    } else {
      const result = scheduleKids(data);
      mainWindow.webContents.send('result-list', JSON.stringify(result));
    }
  });

  // Handle input via the pastebox
  ipcMain.handle('submit-text', async (event, data) => {
    const { allErrors, dataErrors } = handleErrors(data);
    if (!allErrors.every(item => item === false)) {
      mainWindow.webContents.send('error-list', JSON.stringify(dataErrors.getErrorList()));
    } else {
      const result = scheduleKids(data);
      mainWindow.webContents.send('result-list', JSON.stringify(result));
    }
  });

  ipcMain.handle('copy-schedule', async (event, data) => {
    clipboard.writeText(data);
    mainWindow.webContents.send('clipboard-content', 'notification-box');
  });

  ipcMain.handle('export-excel', async (event, data) => {
    // 1. Create a new workbook
    const workbook = new Excel.Workbook();

    // 2. Add a worksheet
    const worksheet = workbook.addWorksheet('My Sheet');

    // 3. Define columns (optional but recommended for object-based row addition)
    worksheet.columns = [
      { header: 'Id', key: 'id', width: 10 },
      { header: 'Name', key: 'name', width: 32 },
      { header: 'Date', key: 'date', width: 15 },
    ];

    // 4. Add data rows
    worksheet.addRow({ id: 1, name: 'John Doe', date: new Date() });
    worksheet.addRow({ id: 2, name: 'Jane Smith', date: new Date() });

    const buffer = await workbook.xlsx.writeBuffer();
    // 5. Save the workbook to the file system
    // await workbook.xlsx.writeFile('output.xlsx');
    const { filePath, canceled } = await dialog.showSaveDialog({
      title: 'Save Workbook',
      filters: [{ name: 'Excel Files', extensions: ['xlsx'] }],
    });
    if (!canceled && filePath) {
      fs.writeFileSync(filePath, buffer);
      console.log('File saved successfully');
    }
  });
  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

const scheduleKids = (data: string) => {
  const kids = new Kids(data);
  const camp = new Camp(kids);
  camp.waterFirst.runAlgo();
  return camp.waterFirst;
};

const handleErrors = (data: string) => {
  const { campData, headerRow } = dataParser(data);
  const dataErrors = new DataErrorHandler(campData, headerRow);
  const allErrors: boolean[] = [
    dataErrors.numOfFields(),
    dataErrors.wrongActivity(),
    dataErrors.notEnoughKids(),
    dataErrors.tooManyKids(),
  ];
  return { allErrors, dataErrors };
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
